version: '3'
services:
  mysql:
    container_name: x3_mysql
    image: 'mysql:8.0.19'
    volumes:
       - './mysql_data:/var/lib/mysql'
    restart: 'always'
    expose:
      - '3307'
    ports:
      - '3307:3306'
    environment:
       MYSQL_ROOT_PASSWORD: 'pass'
       MYSQL_DATABASE: 'test_db'
       MYSQL_USER: 'user'
       MYSQL_PASSWORD: 'pass'

  postgres:
    container_name: x3_postgres
    image: postgres
    restart: 'always'
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - '5433'
    ports:
      - '5433:5432'

  mongo:
    container_name: x3_mongo
    image: mongo
    restart: always
    volumes:
      - './mongo_data:/var/micro-data/mongodb/data/db'
    expose:
      - 27018
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_DATABASE=wqlite
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_NON_ROOT_USERNAME=allen
      - MONGO_NON_ROOT_PASSWORD=pass


  myadmin:
    container_name: x3_admin
    image: 'phpmyadmin/phpmyadmin:5.0.1'
    restart: 'always'
    expose:
      - '8081'
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: pass
